# Generated by Django 4.2.17 on 2025-01-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_react_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='screenshot',
        ),
    ]
